
ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.kajjam.online
CATALOGUE_HOST: catalogue-dev.kajjam.online
REDIS_HOST: redis-dev.kajjam.online
USER_HOST: user-dev.kajjam.online
CART_HOST: cart-dev.kajjam.online
MYSQL_HOST: mysql-dev.kajjam.online
SHIPPING_HOST: shipping-dev.kajjam.online
RABBITMQ_HOST: rabbitmq-dev.kajjam.online
PAYMENT_HOST: payment-dev.kajjam.online
os: redhat