
  - name: appsetup 
    ansible.builtin.import_role:
      name: common
      tasks_from: app-setup.yaml


  - name: NodeJs setup
    ansible.builtin.import_role:
      name: common
      tasks_from: NodeJs-setup.yaml